import Loading from "./Loading";
import Logo from "./Logo";
import Button from "./Button";
import Divider from "./Divider";
import Inputbox from "./InputBox";
import Banner from "./Banner";
import Card from "./Card";
import Pagination from "./Pagination";
import Popularposts from "./Popularposts";
import PopularWriters from "./PopularWriters";
import Navbar from "./Navbar";
import Footer from "./Footer";
import PostComments from "./PostComments";
export {Loading,Logo,Button,Divider,Inputbox,Banner,Card,Pagination,PopularWriters,Popularposts,Navbar,Footer,PostComments};